window.defaultNumber = '+1-888-769-2123';
window.defaultText = 'Your |%model%|  We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. Immediately call Apple Support +1-888-769-2123 to Unblock Your Device!';
window.text = {
    'xhamster.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'perfectgirls.net': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'gotporn.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'anysex.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'sex.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 unlock it!',
    'bravotube.net': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'mylust.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'manporn.xxx': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'anybunny.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'txxx.com': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!',
    'findbestsolution.xyz': 'Your |%model%| We have detected some unusual activities on your Apple device. Your Apple ID has been used in different locations outside the registered country. Hence, for security purposes Access to the device has been blocked. on |%ref%|! Immediately call Apple Support +1-888-769-2123 to unlock it!'
};
